#!/usr/bin/env python3
"""Generate docs/commands.md from skills/*/SKILL.md front matter.

Docs are generated from the actual plugin files so they cannot drift (P-6).
Fails loudly on any mismatch between skills/ on disk and the lifecycle list.
Stdlib only. Run from anywhere.
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
LIFECYCLE = ["init", "prd", "design", "decide", "plan", "implement", "next", "retro", "upgrade"]

HEADER = """\
# Commands

<!-- Generated by scripts/generate-docs.py — do not edit by hand. -->

All commands of the spectacular plugin, in project-lifecycle order.
Recommended models per command: see [models.md](models.md).
"""


def front_matter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not match:
        sys.exit(f"error: {path} has no front matter")
    fields = {}
    for line in match.group(1).splitlines():
        if ":" in line:
            key, value = line.split(":", 1)
            fields[key.strip()] = value.strip()
    return fields


def main() -> None:
    skills_dir = REPO / "skills"
    on_disk = sorted(p.parent.name for p in skills_dir.glob("*/SKILL.md"))
    if on_disk != sorted(LIFECYCLE):
        sys.exit(
            "error: skills on disk do not match the lifecycle list\n"
            f"  on disk:   {on_disk}\n"
            f"  lifecycle: {sorted(LIFECYCLE)}"
        )

    sections = [HEADER]
    for name in LIFECYCLE:
        path = skills_dir / name / "SKILL.md"
        fields = front_matter(path)
        for required in ("name", "description"):
            if required not in fields:
                sys.exit(f"error: {path} front matter lacks '{required}'")
        if fields["name"] != name:
            sys.exit(f"error: {path} front matter name is '{fields['name']}', dir is '{name}'")
        hint = fields.get("argument-hint")
        usage = f"/spectacular:{name} {hint}" if hint else f"/spectacular:{name}"
        sections.append(f"## `{usage}`\n\n{fields['description']}\n")

    out = REPO / "docs" / "commands.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(sections), encoding="utf-8")
    print(f"wrote {out.relative_to(REPO)}")


if __name__ == "__main__":
    main()
